// Vitest Snapshot v1, https://vitest.dev/guide/snapshot.html

exports[`RouteProvider > renders without crashing 1`] = `
<div>
  <h2>
    Unexpected Application Error!
  </h2>
  <h3
    style="font-style: italic;"
  >
    useAuth must be used within an AuthProvider
  </h3>
  <pre
    style="padding: 0.5rem; background-color: rgba(200, 200, 200, 0.5);"
  >
    Error: useAuth must be used within an AuthProvider
    at Module.useAuth (/workspaces/bakso-app/src/shared/hooks/useAuth.ts:9:11)
    at ProtectedRoute (/workspaces/bakso-app/src/shared/components/ProtectedRoute.tsx:8:31)
    at renderWithHooks (/workspaces/bakso-app/node_modules/react-dom/cjs/react-dom.development.js:15486:18)
    at mountIndeterminateComponent (/workspaces/bakso-app/node_modules/react-dom/cjs/react-dom.development.js:20103:13)
    at beginWork (/workspaces/bakso-app/node_modules/react-dom/cjs/react-dom.development.js:21626:16)
    at beginWork$1 (/workspaces/bakso-app/node_modules/react-dom/cjs/react-dom.development.js:27465:14)
    at performUnitOfWork (/workspaces/bakso-app/node_modules/react-dom/cjs/react-dom.development.js:26599:12)
    at workLoopSync (/workspaces/bakso-app/node_modules/react-dom/cjs/react-dom.development.js:26505:5)
    at renderRootSync (/workspaces/bakso-app/node_modules/react-dom/cjs/react-dom.development.js:26473:7)
    at recoverFromConcurrentError (/workspaces/bakso-app/node_modules/react-dom/cjs/react-dom.development.js:25889:20)
  </pre>
  <p>
    ðŸ’¿ Hey developer ðŸ‘‹
  </p>
  <p>
    You can provide a way better UX than this when your app throws errors by providing your own 
    <code
      style="padding: 2px 4px; background-color: rgba(200, 200, 200, 0.5);"
    >
      ErrorBoundary
    </code>
     or
     
    <code
      style="padding: 2px 4px; background-color: rgba(200, 200, 200, 0.5);"
    >
      errorElement
    </code>
     prop on your route.
  </p>
</div>
`;
